services:
  sailing-manager-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 9pYN7F9e2k3K8Hd
      POSTGRES_USER: djangouser
      POSTGRES_DB: dorchester_django

  sailing-manager-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  sailing-manager-web:
    image: sailing-manager
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT: production
      WEBHOST: dorchester.sailmanager.co.uk
      SECRET_KEY: '6$$oc8gs$$tcm(07krs7(9)bek5j)9b-8$$vhq70coz&p4mm4yda!'
      DB_NAME: dorchester_django
      DB_USER: djangouser
      DB_PASS: 9pYN7F9e2k3K8Hd
      DB_HOST: sailing-manager-db
    volumes:
      - /var/www/sailing-manager-docker/static:/sailmanager/staticfiles
