# Generated by Django 3.2.6 on 2021-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0002_remove_race_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='StartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
