# Generated by Django 3.2.6 on 2021-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0004_alter_race_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='StartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
