# Generated by Django 3.2.6 on 2021-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0007_alter_race_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='SignedUpBy',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
