# Generated by Django 3.2.6 on 2021-12-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0009_alter_official_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Official', to='SailingRaceManager.official')),
                ('Race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Race_official', to='SailingRaceManager.race')),
            ],
        ),
    ]
