# Generated by Django 3.2.6 on 2022-01-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0010_officialevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['BoatName']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-Date', 'RaceNumber']},
        ),
    ]
