# Generated by Django 3.2.6 on 2025-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0011_auto_20220106_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='Status',
            field=models.IntegerField(choices=[(0, 'FINISHED'), (1, 'RETIRED'), (2, 'DID NOT START'), (3, 'RACING')], default=3),
        ),
    ]
