# Generated by Django 3.2.6 on 2021-08-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceNumber', models.PositiveIntegerField(default=1)),
                ('StartTime', models.DateTimeField()),
                ('RaceLength', models.PositiveIntegerField(default=40)),
                ('RaceType', models.CharField(choices=[(0, 'Handicap'), (1, 'Pursuit')], default=0, max_length=20)),
            ],
        ),
    ]
