# Generated by Django 3.2.6 on 2021-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0002_alter_race_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='RaceType',
            field=models.CharField(choices=[('0', 'Handicap'), ('1', 'Pursuit')], default=0, max_length=20),
        ),
    ]
