# Generated by Django 3.2.6 on 2021-10-30 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0003_race_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='StartTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
