# Generated by Django 3.2.6 on 2021-08-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0003_alter_race_racetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='StartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
