# Generated by Django 3.2.6 on 2021-08-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0004_alter_race_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='RaceNumber',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
