# Generated by Django 3.2.6 on 2021-08-22 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SailingRaceManager', '0005_alter_race_racenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='RaceType',
            field=models.IntegerField(choices=[(0, 'Handicap'), (1, 'Pursuit')], default=0),
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LapsComplete', models.PositiveIntegerField(default=0)),
                ('FinishTime', models.DateTimeField(blank=True, null=True)),
                ('Status', models.IntegerField(choices=[(0, 'FINISHED'), (1, 'RETIRED'), (2, 'DID NOT START')])),
                ('Race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Race', to='SailingRaceManager.race')),
                ('Racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Racer', to='SailingRaceManager.race')),
            ],
        ),
    ]
