# Generated by Django 3.2.6 on 2021-08-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0006_auto_20210822_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoatName', models.CharField(max_length=50)),
                ('PyNumber', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='Racer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Racer', to='SailingRaceManager.racer'),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='Status',
            field=models.IntegerField(blank=True, choices=[(0, 'FINISHED'), (1, 'RETIRED'), (2, 'DID NOT START')], null=True),
        ),
    ]
