# Generated by Django 3.2.6 on 2021-08-22 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SailingRaceManager', '0007_auto_20210822_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PY',
            new_name='Boat',
        ),
        migrations.AddField(
            model_name='racer',
            name='Boat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Boat', to='SailingRaceManager.boat'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
