# Generated by Django 3.2.6 on 2021-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0008_auto_20210822_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='User',
        ),
        migrations.AddField(
            model_name='racer',
            name='CrewName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='HelmName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='SailNumber',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
