# Generated by Django 3.2.6 on 2021-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0009_auto_20210830_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='StartTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
