# Generated by Django 3.2.6 on 2021-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SailingRaceManager', '0010_alter_race_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='CrewName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
